name: xyz.mackan.ChatItem.ChatItem
version: 1.0.1
main: xyz.mackan.ChatItem.ChatItem
description: A plugin that lets you show items in chat
author: Mackan
depend: [LocaleLib]
api-version: 1.16
